site_name: Matt Wetzel - Azure Portfolio
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: index.md
  - How this site was made:
    - Overview: projects/index.md
    - Creating the App Service: projects/appservice.md
    - Creating the Storage Account: projects/storageaccount.md
    - Creating the VNET: projects/vnet.md
    - Setting up GitHub Actions for CI/CD: projects/githubactions.md
    - Initializing the environment using MKDocs: projects/mkdocs.md
    - Configuring Custom Domain and SSL: projects/custom.md